import{a as v,S,i as n}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const E="50309673-ea2b029f8f1cb6745c8643ce8",R="https://pixabay.com/api/",$=15;async function f(o,r=1){const e={key:E,q:o.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:$};return(await v.get(R,{params:e})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");let q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const r=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
          <div class="image-info">
            <p><b>Likes:</b>👍 ${e.likes}</p>
            <p><b>Views:</b>👀 ${e.views}</p>
            <p><b>Comments:</b>💬 ${e.comments}</p>
            <p><b>Downloads:</b>⬇️ ${e.downloads}</p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function M(){m.innerHTML=""}function y(){g.classList.add("visible")}function b(){g.classList.remove("visible")}function L(){h.classList.remove("hidden")}function i(){h.classList.add("hidden")}const w=document.querySelector(".form"),B=document.querySelector(".load-more-btn"),A=document.querySelector(".gallery");let d="",a=1,u=0;const P=15;w.addEventListener("submit",O);B.addEventListener("click",_);async function O(o){o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}d=r,a=1,M(),i(),y();try{const e=await f(d,a);if(e.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=e.totalHits,p(e.hits),u>P?L():i()}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{b(),w.reset()}}async function _(){a+=1,y(),i();try{const o=await f(d,a);p(o.hits);const r=Math.ceil(u/P);a>=r?(i(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L();const{height:e}=A.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}finally{b()}}
//# sourceMappingURL=index.js.map
